Updated Sarus MPI checks using SSH
eth-cscs/cscs-reframe-tests pull request #125
Opened 2023-09-28 12:18 UTC by Madeeks

Not all clusters have the scratch filesystem mounted to `/scratch`, so the `$SCRATCH` environment variable should be used when defining the bind mount option. This is also consistent with the bash commands being executed in the container.

2023-09-28 13:47 UTC, lucamar commented
@jenkins-cscs retry daint

2023-09-28 14:21 UTC, teojgo requested changes

2023-09-28 14:21 UTC, teojgo commented on checks/containers/sarus/check_osu_benchmarks.py
> +            '--mount=src=$SCRATCH,dst=$SCRATCH,type=bind',
```suggestion
            '--mount=src=${SCRATCH:-/scratch},dst=${SCRATCH:-/scratch},type=bind',
```

2023-10-02 16:17 UTC, teojgo approved these changes

2023-10-02 16:17 UTC, merged