[clariden] pytorch ddp CE test
eth-cscs/cscs-reframe-tests pull request #161
Opened 2024-02-13 12:52 UTC by henrique

2024-02-13 14:14 UTC, teojgo commented
cscs-ci run alps-cpe-tests

2024-02-13 16:28 UTC, henrique commented
cscs-ci run alps-cpe-tests

2024-02-14 10:37 UTC, jgphpc commented
cscs-ci run alps-cpe-tests

2024-02-14 10:42 UTC, teojgo requested changes

2024-02-14 10:42 UTC, teojgo commented on checks/apps/pytorch/pytorch_amd.py
> +
Remove one blank line

2024-02-14 10:42 UTC, teojgo commented on checks/apps/pytorch/pytorch_nvidia.py
> +
Remove one blank line

2024-02-14 10:42 UTC, teojgo commented on checks/apps/pytorch/pytorch_nvidia.py
> +
Remove one blank line

2024-02-14 10:42 UTC, teojgo commented on checks/apps/pytorch/pytorch_nvidia.py
> +import os
This is not used

2024-02-15 08:35 UTC, henrique commented
cscs-ci run alps-cpe-tests

2024-02-19 17:00 UTC, henrique commented
the AMD tests were failing repeatedly and randomly, so I removed them for now (I will create a separated PR for that)
all remaining [NVIDIA] tests passed
cheers!

2024-02-20 11:02 UTC, henrique commented
ok, finally everything passed!
the amd tests have to go on another PR, as they seemed a bit unstable.
Cheers!

2024-02-20 13:19 UTC, henrique commented on checks/apps/pytorch/pytorch_nvidia.py
> +    aws_ofi_nccl = parameter([True, False])
I thought it didn't hurt and it might be useful data in case of a regression

2024-02-21 07:51 UTC, merged