[clariden] PyTorch Amd tests
eth-cscs/cscs-reframe-tests pull request #175
Opened 2024-02-28 16:12 UTC by henrique

2024-02-28 17:45 UTC, henrique commented
cscs-ci run alps-cpe-tests

2024-02-29 08:59 UTC, teojgo commented on checks/apps/pytorch/pytorch_amd.py
> +class PyTorchDdpPipAmd(PyTorchAmdTestBase):
We may need to restrict this since this requires a cpe to be there.

2024-02-29 13:03 UTC, teojgo commented on checks/apps/pytorch/pytorch_amd.py
> +    torch_version = parameter([
yes, the problem with the large parameter is that it shows also at the test name so it become huge

2024-02-29 17:20 UTC, teojgo requested changes

2024-02-29 17:20 UTC, teojgo commented on checks/apps/pytorch/pytorch_amd.py
> +            'pip install torch torchvision --index-url '
```suggestion
            f'pip install torch torchvision --index-url '
```

2024-03-04 09:04 UTC, teojgo approved these changes

2024-03-04 09:24 UTC, merged