Simplify affinity test
eth-cscs/cscs-reframe-tests pull request #182
Opened 2024-04-08 07:00 UTC by ekouts

2024-04-17 13:53 UTC, teojgo requested changes

2024-04-17 13:53 UTC, teojgo commented on checks/prgenv/affinity_check.py
> +    It setus up the processor's topology, based on the configuration.
```suggestion
    It sets up the processor's topology, based on the configuration.
```

2024-04-17 15:13 UTC, jgphpc commented
+ run pycodestyle

2024-04-18 06:12 UTC, ekouts commented
> command to reproduce please

I just run it on daint/eiger, since they are the only available machines for.

2024-04-18 07:46 UTC, teojgo approved these changes

2024-04-18 07:50 UTC, merged