Add slurm queue test availability
eth-cscs/cscs-reframe-tests pull request #4
Opened 2022-06-03 19:53 UTC by victorusu

These tests expect
* all partitions listed to be present in a given system (even if
they are not accessible)
* at least one node per partition to be in allocated, reserved, and/or
idle state
* no more than 10% of compute nodes assigned to a partition to be in
a state other than allocated, reserved, and/or idle

2022-06-09 09:32 UTC, ekouts requested changes
lgtm in general, but maybe we can add the dependencies that you mentioned in slack. If this test fails there is no point on running the `HostnameCheck` since it will block the ci

2022-06-09 09:51 UTC, vkarak commented
> - at least one node per partition to be in allocated, reserved, and/or
idle state
> - no more than 10% of compute nodes assigned to a partition to be in
a state other than allocated, reserved, and/or idle

I don't understand the difference of these two. It seems that the second one overrides the first one.

2022-06-09 11:04 UTC, vkarak requested changes

2022-06-24 11:23 UTC, vkarak reviewed
Lgtm, I have just a minor comment.

2022-06-24 11:23 UTC, vkarak commented on checks/system/slurm/slurm.py
> +                                f'partition {self.current_system.name}')
Perhaps?

```suggestion
                                f'partition {self.current_partition.fullname}')
```

2022-06-30 07:53 UTC, victorusu commented
> lgtm in general, but maybe we can add the dependencies that you mentioned in slack. If this test fails there is no point on running the `HostnameCheck` since it will block the ci

@ekouts, to make this happen, I need to change the `HostnameCheck` fundamentally... This I will do in another PR.

2022-06-30 07:54 UTC, ekouts approved these changes

2022-07-15 11:49 UTC, victorusu commented
@jenkins-cscs retry all

2022-07-15 14:31 UTC, teojgo approved these changes

2022-07-15 14:31 UTC, merged