Add cray module to load singularity
eth-cscs/cscs-reframe-tests pull request #70
Opened 2023-05-11 16:20 UTC by lucamar

The check `ContainerMpichOSUTest` fails on Pilatus in the [daily run of the regression test suite](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/656/pipeline):
```
Lmod Warning: Failed to find the following module(s):
"singularity/3.5.3-eiger" in your MODULEPATH

Try:
    $ module spider singularity/3.5.3-eiger
to see if the module(s) are available across all compilers and MPI implementations.
```
The reason is that the module `cray` is not loaded, since the module `singularity` is not created in a toolchain with a `PrgEnv` modulefile: therefore I am adding the request to load the module `cray` in the initialization of the check.

2023-05-11 16:52 UTC, lucamar commented
The CI still fails with the same error message, I am likely missing something in the fix: could you please have a look @teojgo?

2023-05-12 10:14 UTC, lucamar commented
I have changed the configuration file of Pilatus following @teojgo's advice, now the CI passed.

2023-05-12 10:42 UTC, teojgo requested changes
It looks good to me, thanks @lucamar

2023-05-12 10:44 UTC, teojgo approved these changes

2023-05-12 10:44 UTC, merged