[cpe/alps] netcdf-hdf5-parallel
eth-cscs/cscs-reframe-tests pull request #84
Opened 2023-06-01 12:31 UTC by jgphpc

https://jira.cscs.ch/browse/VCMSA-319 (part2)
Current test codes are serial -> moving to parallel tests, for example:
```
    https://github.com/Unidata/netcdf-c/blob/main/examples/C/simple_xy_wr.c
    https://github.com/Unidata/netcdf-c/blob/main/examples/C/simple_xy_rd.c
    -> https://github.com/Unidata/netcdf-c/blob/main/nc_test4/tst_parallel.c
```

2023-06-01 12:43 UTC, jgphpc commented on checks/libraries/io/netcdf.py
> +                'LD_PRELOAD': '/opt/cray/pe/gcc/12.2.0/snos/lib64/libstdc++.so'
🤮 but I can't find a better way

2023-06-05 12:47 UTC, teojgo requested changes

2023-06-05 12:47 UTC, teojgo commented on checks/libraries/io/netcdf.py
> +        self.executable = 'wr.exe'
This can go at a class level

2023-06-05 12:47 UTC, teojgo commented on checks/libraries/io/netcdf.py
> +                'LD_PRELOAD': '/opt/cray/pe/gcc/12.2.0/snos/lib64/libstdc++.so'
'LD_PRELOAD': '$GCC_PREFIX/snos/lib64/libstdc++.so'

2023-06-13 08:29 UTC, teojgo reviewed
Overall it looks good. The only problem that I see is that it's tied to cray specific paths/prg envs so it won't work without a cray environment.

2023-06-13 11:26 UTC, jgphpc commented
> Overall it looks good. The only problem that I see is that it's tied to cray specific paths/prg envs so it won't work without a cray environment.

we can fix that when we update the test for uenv

2023-06-20 06:44 UTC, ekouts approved these changes

2023-06-20 06:46 UTC, merged